# Generated by Django 6.1.1 on 2026-09-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('pages', models.IntegerField(default=0)),
                ('dimensions', models.JSONField(default=list)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='web.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('crawl', 'Crawl'), ('recrawl', 'Re-crawl'), ('report', 'Report')], max_length=10)),
                ('url', models.CharField(blank=True, max_length=2000)),
                ('dimensions', models.JSONField(default=list)),
                ('run', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='running', max_length=10)),
                ('label', models.TextField(blank=True)),
                ('step', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
                ('done', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='web.site')),
            ],
            options={
                'ordering': ['-started'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'running')), fields=('site',), name='one_running_job_per_site')],
            },
        ),
    ]
