# Generated by Django 6.1.1 on 2026-09-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='icp',
            field=models.TextField(blank=True, verbose_name='ICP'),
        ),
    ]
