# Generated by Django 6.1.1 on 2026-09-26 15:24

import companyscan.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_site_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='aliases',
            field=models.TextField(blank=True, help_text='Former names, product names, short forms; one per line', verbose_name='Other names'),
        ),
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.CharField(blank=True, help_text='What kind of business, e.g. growth advisory for SaaS CEOs', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='people',
            field=models.TextField(blank=True, help_text='Founders or principals, one per line'),
        ),
        migrations.AddField(
            model_name='site',
            name='profiles',
            field=models.TextField(blank=True, help_text='LinkedIn, Crunchbase, G2, Google Business Profile URLs; one per line', validators=[companyscan.web.models.validate_urls], verbose_name='Official profiles'),
        ),
    ]
