# Generated by Django 6.1.1 on 2026-09-27 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_site_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='customer_ltv',
            field=models.PositiveIntegerField(blank=True, help_text='What one new customer is worth over the relationship', null=True, verbose_name='Customer lifetime value ($)'),
        ),
        migrations.AddField(
            model_name='site',
            name='place_id',
            field=models.CharField(blank=True, help_text='Filled in by the first crawl that finds the Google listing; clear it to search again', max_length=255, verbose_name='Google place ID'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_read',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='target_customers',
            field=models.PositiveIntegerField(blank=True, help_text='How many new customers the business wants to win, e.g. this year', null=True, verbose_name='New customers wanted'),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('icp', models.TextField(blank=True, verbose_name='ICP')),
                ('location', models.CharField(blank=True, max_length=310)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('items', models.JSONField(blank=True, default=list)),
                ('run', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='web.site')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('checks', models.JSONField(default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='web.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
