# Generated by Django 6.1.1 on 2026-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_reuse_and_scorecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='target_customers',
            field=models.PositiveIntegerField(blank=True, help_text='How many new customers the business wants to win in a year', null=True, verbose_name='New customers wanted per year'),
        ),
    ]
