# Generated by Django 6.1.1 on 2026-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_customers_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
    ]
