# Generated by Django 6.1.1 on 2026-10-06 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_site_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='blog_every_days',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to stop drafting posts', null=True, verbose_name='Blog post every N days'),
        ),
        migrations.AddField(
            model_name='site',
            name='blog_per_run',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Posts per run'),
        ),
        migrations.AddField(
            model_name='site',
            name='blog_repeat_keywords',
            field=models.BooleanField(default=False, help_text='Allow a keyword again once every keyword was used in the last posts', verbose_name='Reuse keywords'),
        ),
        migrations.AddField(
            model_name='site',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords to write posts for, one per line'),
        ),
        migrations.AddField(
            model_name='site',
            name='offering',
            field=models.TextField(blank=True, verbose_name='What the business does'),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('crawl', 'Crawl'), ('recrawl', 'Re-crawl'), ('report', 'Report'), ('blog', 'Blog posts')], max_length=10),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('keyword', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('run', models.CharField(blank=True, max_length=255)),
                ('profile', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='web.site')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
