# Generated by Django 6.1.1 on 2026-10-06 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_blog_posts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, help_text='Main business phone; compared with the Google listing', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('crawl', 'Crawl'), ('recrawl', 'Re-crawl'), ('report', 'Report'), ('blog', 'Blog posts'), ('google', 'Google sync')], max_length=10),
        ),
        migrations.CreateModel(
            name='GoogleConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_connections', to='web.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('location_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='web.googleconnection')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('field_edit', 'Listing edit'), ('review_reply', 'Review reply'), ('qna_answer', 'Question answer'), ('claim_start', 'Start claim')], max_length=20)),
                ('target', models.CharField(max_length=255)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='web.googlelocation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='googleconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('site',), name='one_active_google_connection_per_site'),
        ),
    ]
