# Generated by Django 6.1.1 on 2026-10-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_google_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('stub', 'Planned'), ('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('crawl', 'Crawl'), ('recrawl', 'Re-crawl'), ('report', 'Report'), ('blog', 'Blog posts'), ('titles', 'Blog titles'), ('google', 'Google sync')], max_length=10),
        ),
    ]
