# Generated by Django 6.1.1 on 2026-10-06 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_blog_stubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('wordpress', 'WordPress'), ('shopify', 'Shopify'), ('webflow', 'Webflow'), ('squarespace', 'Squarespace'), ('wix', 'Wix'), ('other', 'Other')], max_length=20)),
                ('admin_url', models.URLField(max_length=500)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('secret', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='web.site')),
            ],
        ),
    ]
