# Generated by Django 6.1.1 on 2026-10-06 14:29

import companyscan.web.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_site_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="How code refers to it, and the output file's name", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this agent is for; not sent to the model')),
                ('prompt', models.TextField(help_text='The system prompt: what to do, and what each output field must contain')),
                ('model', models.CharField(default='openai:gpt-5-mini', help_text='provider:model, e.g. openai:gpt-5-mini', max_length=100)),
                ('temperature', models.FloatField(blank=True, help_text="Blank for the model's default; some models reject a temperature", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('context', models.JSONField(blank=True, default=dict, help_text='Static context, merged under whatever the caller passes')),
                ('output_schema', models.JSONField(blank=True, default=companyscan.web.models.default_schema, help_text='JSON Schema of the answer, e.g. {"properties": {"angle": {"type": "string"}}}. Every declared property is required unless the schema lists "required".')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='web.agent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
